apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  creationTimestamp: null
  labels:
    machine.openshift.io/cluster-api-cluster: <infrastructure_id> 
  name: <infrastructure_id>-infra 
  namespace: openshift-machine-api
spec:
  replicas: <infra_node_replicas>
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: <infrastructure_id> 
      machine.openshift.io/cluster-api-machineset: <infrastructure_id>-infra 
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: <infrastructure_id> 
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra 
        machine.openshift.io/cluster-api-machineset: <infrastructure_id>-infra 
    spec:
      metadata:
        creationTimestamp: null
        labels:
          mymachineconfigpool/infra: ""
          node-role.kubernetes.io/infra: "" 
      taints: 
      - key: node-role.kubernetes.io/infra
        effect: NoSchedule
      providerSpec:
        value:
          apiVersion: vsphereprovider.openshift.io/v1beta1
          credentialsSecret:
            name: vsphere-cloud-credentials
          diskGiB: <infra_diskgib>
          kind: VSphereMachineProviderSpec
          memoryMiB: <infra_mem>
          metadata:
            creationTimestamp: null
          network:
            devices:
            - networkName: "<vcenter_vm_network_name>" 
          numCPUs: <infra_cpu>
          numCoresPerSocket: <infra_cpu_core>
          snapshot: ""
          template: "<vcenter_vm_template_name>"
          userDataSecret:
            name: worker-user-data
          workspace:
            datacenter: "<vcenter_datacenter_name>" 
            datastore: "<vcenter_datastore_name>"
            folder: "<vcenter_vm_folder_path>"
            resourcepool: "<vcenter_resource_pool>" 
            server: "<vcenter_server_ip>"