apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: rhodf
spec:
  machineConfigSelector:
    matchExpressions:
      - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,rhodf]} 
  nodeSelector:
    matchLabels:
      mymachineconfigpool/rhodf: ""