apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  creationTimestamp: null
  labels:
    machine.openshift.io/cluster-api-cluster: <infrastructure_id> 
  name: <infrastructure_id>-rhodf 
  namespace: openshift-machine-api
spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: <infrastructure_id> 
      machine.openshift.io/cluster-api-machineset: <infrastructure_id>-rhodf 
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: <infrastructure_id>
        machine.openshift.io/cluster-api-machine-role: rhodf
        machine.openshift.io/cluster-api-machine-type: rhodf
        machine.openshift.io/cluster-api-machineset: <infrastructure_id>-rhodf 
    spec:
      metadata:
        creationTimestamp: null
        labels:
          cluster.ocs.openshift.io/openshift-storage: ""
          mymachineconfigpool/rhodf: ""
          node-role.kubernetes.io/rhodf: ""
          node-role.kubernetes.io/infra: ""
      taints: 
      - key: node.ocs.openshift.io/storage
        value: 'true'
        effect: NoSchedule
      providerSpec:
        value:
          apiVersion: vsphereprovider.openshift.io/v1beta1
          credentialsSecret:
            name: vsphere-cloud-credentials
          diskGiB: <odf_diskgib>
          kind: VSphereMachineProviderSpec
          memoryMiB: <odf_mem>
          metadata:
            creationTimestamp: null
          network:
            devices:
            - networkName: "<vcenter_vm_network_name>" 
          numCPUs: <odf_cpu>
          numCoresPerSocket: <odf_cpu_core>
          snapshot: ""
          template: "<vcenter_vm_template_name>"
          userDataSecret:
            name: worker-user-data
          workspace:
            datacenter: "<vcenter_datacenter_name>" 
            datastore: "<vcenter_datastore_name>"
            folder: "<vcenter_vm_folder_path>"
            resourcepool: "<vcenter_resource_pool>" 
            server: "<vcenter_server_ip>"